### ISSUE TITLE
How to merge xaml file in project with 2 libraries?

### ISSUE THREAD

**Issue by ghost1372** [batzen/XAMLTools#87]
I was trying to merge a project
Solution
    --ProjectA
    --ProjectB

ProjectA contains Styles and Custom Controls, some of Custom controls is based on Custom Styles.
i merged Custom Styles into a CombinedResource.xaml file, and all custom controls into generic.xaml

i was able to run app, but opening/using custom controls, crash app due to lack of resources (resource not found exception)

--

ProjectB contains Custom controls and some of them use Custom styles from ProjectA, i merged all custom controls into generic.xaml file.
after running app, i get exception for custom controls because of lack of resources (resource not found exception)

for example i saw that in custom controls we refrenced styles like this:

```
 <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="/iNKORE.UI.WPF.Modern;component/Themes/Styles/TextBox.xaml" />
    </ResourceDictionary.MergedDictionaries>
```

i changed TextBox to CombinedResource.xaml and app worked fine. but this is not a good idea, we have a lot of files and what happened if i put combinedresources.xaml in each file !!?

So I'm looking for the answer, how to merge resources in this project?

**Comment by batzen** [comment]
I don't fully understand your question.

What i do in my projects is:
- include MergedDictionaries where needed for development time (that's why the source files that should be combined are still compiled as pages/xaml files during debug builds).
- do not use `ImportMergedResourceDictionaryReferences`

When you don't use `ImportMergedResourceDictionaryReferences` everything should be fine in the combined xaml file.
The main purpose of XAMLCombine is to get rid of MergedDictionaries as that slows down loading performance.

In Fluent.Ribbon i merge everything (Resources, Styles etc.) to Styles.xaml and provide a Generic.xaml that uses MergedDictionaries.
Everything outside the project (Fluent.Ribbon) just references the Generic.xaml and nothing else.
Referencing something other than the combined XAML file wouldn't even be possible if not building in debug mode as the single files are not part of the compilation at all.

I hope that answers your question.

**Comment by ghost1372** [comment]
thank you
if it is possible try to merge this project
https://github.com/InkoreStudios/UI.WPF.Modern

this
https://github.com/InkoreStudios/UI.WPF.Modern/tree/main/source/iNKORE.UI.WPF.Modern

and this one
https://github.com/InkoreStudios/UI.WPF.Modern/tree/main/source/iNKORE.UI.WPF.Modern.Controls

**Comment by batzen** [comment]
You mean merging everything in [iNKORE.UI.WPF.Modern](https://github.com/InkoreStudios/UI.WPF.Modern/tree/main/source/iNKORE.UI.WPF.Modern) to `Theme.xaml` and everything in [iNKORE.UI.WPF.Modern.Controls](https://github.com/InkoreStudios/UI.WPF.Modern/tree/main/source/iNKORE.UI.WPF.Modern.Controls) to `Generic.xaml` and then using those two files only?

If that's the case, it works properly if you remove all the nested dictionaries you are currently using for your converters and then disable/remove `ImportMergedResourceDictionaryReferences`.
I just tested it with a modified version of my tools where nested dictionaries without a `Source` attribute are always included when merging. At least your sample application runs and as far as i can judge from a quick test everything works as it should.

**Comment by ghost1372** [comment]
iNKORE.UI.WPF.Modern has Generic.xaml and a ControlsResources.xaml
and iNKORE.UI.WPF.Modern.Controls only has Generic.xaml
in TextContextMenu.xaml file which is a Custom Control and refrenced in Generic.xaml we have a refrence to Style
 https://github.com/InkoreStudios/UI.WPF.Modern/blob/main/source/iNKORE.UI.WPF.Modern/Themes/TextContextMenu.xaml

 ```
<ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="/iNKORE.UI.WPF.Modern;component/Themes/Styles/ContextMenu.xaml" />
    </ResourceDictionary.MergedDictionaries>
```

and this is same for controls in  `iNKORE.UI.WPF.Modern.Controls` 

i should test it again with your details. also does this property **ImportMergedResourceDictionaryReferences** enabled by default? because i did not touch this property.

**Comment by ghost1372** [comment]
can you upload latest changes to nuget? i want to test it again

**Comment by batzen** [comment]
Just published https://www.nuget.org/packages/XAMLTools.MSBuild/1.0.0-alpha0164.
Might take some time for the indexing to be completed.

For testing purposes you can also use the nuget feed from the CI build by adding https://ci.appveyor.com/nuget/xamltools as a nuget source. ;-)

**Comment by batzen** [comment]
`ImportMergedResourceDictionaryReferences` is off by default.
I had to turn it on to get your nested converter dictionaries to be included in the result.
But as i already said you should better remove those nested dictionaries to improve performance.

**Comment by ghost1372** [comment]
@batzen 
i forked mentioned repo and i pushed a commit
https://github.com/ghost1372/UI.WPF.Modern

please clone this repo and try to run demo

i moved all converters outside of MergedDictionary

i merged all xaml files in **iNKORE.UI.WPF.Modern** into Generic.xaml

i merged all xaml files in **iNKORE.UI.WPF.Modern.Controls** into Generic.xaml

it seems that  **iNKORE.UI.WPF.Modern**  merged correctly and we dont have any issue for this lib. but we get exception for  **iNKORE.UI.WPF.Modern.Controls** 

### Issue 1
demo app will be opened, and all Styles will be opened without any issues (for example: Button, ComboBox Pages.)

![image](https://github.com/batzen/XAMLTools/assets/9213496/0ce92223-8f43-4d8f-875d-c0fe21e1ae82)


**But** if you navigate to Custom controls (for example DropDownButton, SplitButton, AutoSuggestBox, InfoBar, MenuFlyout Pages) you can see that app will be crash and we get resource not found exception 

![image](https://github.com/batzen/XAMLTools/assets/9213496/c21f6710-1f86-436e-ae71-e5e070a57367)


### Issue 2

if we change **Debug** to **Release** Mode demo app will be crash and get resource not found exception

### Issue 3
i used **ImportMergedResourceDictionaryReferences** and there is an issue, as you can see we have duplicate items:

![Screenshot 2023-12-02 193330](https://github.com/batzen/XAMLTools/assets/9213496/7f88adcd-93be-43bf-9bd9-6af7eab37b1e)

**Comment by ghost1372** [comment]
@batzen  i also get error when i want to use ImportMergedResourceDictionaryReferences

i removed bin, obj folder and i closed vs and reopened it but i get this error again

```
XAMLCombine_Exception	System.Exception: Error during Resource Dictionary saving: {0} ---> System.IO.IOException: The process cannot access the file 'E:\Github Clone\UI.WPF.Modern\source\Inkore.UI.WPF.Modern.Controls\Themes\Generic.xaml' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at XAMLTools.XAMLCombine.XAMLCombiner.WriteResultFile(String resultFile, XDocument finalDocument) in C:\projects\xamltools\src\XAMLTools.Core\XAMLCombine\XAMLCombiner.cs:line 527
   --- End of inner exception stack trace ---
   at XAMLTools.XAMLCombine.XAMLCombiner.WriteResultFile(String resultFile, XDocument finalDocument) in C:\projects\xamltools\src\XAMLTools.Core\XAMLCombine\XAMLCombiner.cs:line 541
   at XAMLTools.XAMLCombine.XAMLCombiner.Combine(IReadOnlyCollection`1 sourceFiles, String targetFile) in C:\projects\xamltools\src\XAMLTools.Core\XAMLCombine\XAMLCombiner.cs:line 356
   at XAMLTools.Helpers.MutexHelper.ExecuteLocked[T](Func`1 action, String file, String caller, Nullable`1 timeout, String errorMessage) in C:\projects\xamltools\src\XAMLTools.Core\Helpers\MutexHelper.cs:line 25
   at XAMLTools.MSBuild.XAMLCombineTask.Execute() in C:\projects\xamltools\src\XAMLTools.MSBuild\XAMLCombineTask.cs:line 55	iNKORE.UI.WPF.Modern.Controls		1	
```

**Comment by batzen** [comment]
I don't know why you got duplicate entries in the generic.xaml as the tools have guards against duplicating merged dictionaries.

The runtime error is quite interesting.
It happens because, for whatever reason, WPF decides to load the theme resources in reverse order.
I am currently investigating this.

**Comment by ghost1372** [comment]
if i use **ImportMergedResourceDictionaryReferences** in **Debug** mode app will be compiled without any error, but we have duplicate items.
and if i use **Release** Mode, app can not compile and i get error and mentioned exception

**Comment by batzen** [comment]
Ok. I found out what's happening.
Previously things like `TitleBarControl.xaml` was included in `Generic.xaml` from `iNKORE.UI.WPF.Modern` but not in it's `ControlsResources`.
This led to a "correct" order of loaded `GenericResourceDictionaries` because `Generic.xaml` from `iNKORE.UI.WPF.Modern` was loaded first.
Now that everything is contained in the `Generic.xaml` from `iNKORE.UI.WPF.Modern` (and `iNKORE.UI.WPF.Modern.Controls`) there is no lookup at the system level because the required resources are all immediately found.
Especially because `XamlControlsResources` loads the `Generic.xaml` from `iNKORE.UI.WPF.Modern`.

The resource loading is triggered by `SetWindowStyle` from `WindowHelper` which then triggers the load of the `MicaWindowStyle` which then triggers the load of the values for it's `WindowChrome` which then triggers the load of `primitives:TitleBar.HeightKey`. That last key was previously only found in the stripped down `Generic.xaml` from `iNKORE.UI.WPF.Modern`.
Because of this the load order of the dictionaries in `GenericResourceDictionaries` was `PresentationFramework`, `iNKORE.UI.WPF.Modern` and then `iNKORE.UI.WPF.Modern.Controls`.

Now, because the resources are all contained in the two generic dictionaries is `iNKORE.UI.WPF.Modern.Controls`, `iNKORE.UI.WPF.Modern` and then `PresentationFramework`.
Because `iNKORE.UI.WPF.Modern.Controls` references resources from `iNKORE.UI.WPF.Modern` the resource lookup at the generic level fails as `iNKORE.UI.WPF.Modern` is placed after `iNKORE.UI.WPF.Modern.Controls`.

There are several ways of solving this issue:
1. Merge the assemblies `iNKORE.UI.WPF.Modern` and `iNKORE.UI.WPF.Modern.Controls` to one assembly. That way there is only one `Generic.xaml` instead of two that rely one another.
2. Include both `Generic.xaml` files from `iNKORE.UI.WPF.Modern` and `iNKORE.UI.WPF.Modern.Controls` in `App.xaml` and remove the custom loading loading code.
3. Try to find out how to get everything loaded in the desired order. Maybe all of this is somehow related to the custom resource loading code

It took me a couple of hours of debugging deep inside the resource retrieval code of WPF to get this far.
IMHO way 1. would be the best solution as the namespaces are already mixed, which was very confusing during my analysis.
The quick start guide also says you have to reference both assemblies.
I don't know why the code is split into two assemblies.

**Comment by ghost1372** [comment]
Thank you i will consider option 1 and i should talk with library developer
🙏🙏
